[package]
name = "frontend"
version = "0.1.0"
edition = "2021"
authors = ["Jon-Mycal Palmer"]


[dependencies]
backend = { path = "../backend"}

eframe = "0.19.0"
chrono = "0.4.22"
itertools = "0.10.5"
